apiVersion: v1
kind: Service
metadata:
  name: {{ include "fwv-central-api-chart.fullname" . }}-fwvapi
spec:
  type: {{ .Values.fwvapi.service.type | default "ClusterIP" }}
  ports:
    - port: 5001
      targetPort: 5001
      protocol: TCP
      nodePort: {{.Values.fwvapi.hostPort}}
  selector:
    app: {{ include "fwv-central-api-chart.name" . }}-fwvapi
