postgresdb:
  replicaCount: 1

  image:
    repository: postgres
    tag: latest
    pullPolicy: IfNotPresent

  credentials:
     username: postgres
     password: Password1!

  service:
    enabled: true
    type: ClusterIP
    port: 5432

  storage:
    size: 1Gi  # Specify the storage size you need
    accessModes:
      - ReadWriteOnce
    storageClassName: local-path  # Adjust this if you have a specific storage class; "standard" is common

pgadmin:
  replicaCount: 1

  image:
    repository: dpage/pgadmin4
    tag: latest
    pullPolicy: IfNotPresent

  credentials:
    email: admin@flikweertvision.nl
    password: admin

  service:
    type: NodePort
    hostPort: 32500

fwvconsumer:
  replicaCount: 1

  image: 
    repository: docker.io/flikweertvision/fv_consumer
    tag: latest
    pullPolicy: IfNotPresent
  
  environment:
    pg_db_host: postgresdb
    pg_db_user: postgres
    pg_db_password: "Password1!"
    pg_db_port: 5432
    pg_db_name: postgres
    mssql_db_host: ""
    mssql_db_user: ""
    mssql_db_password: "" 
    mssql_db_database: "" 
    mssql_db_port: ""
    rmq_username: "consumer"
    rmq_password: "consumer"
    rmq_host: rmq
    rmq_port: 5672

fwvapi:
  replicaCount: 1

  image:
    repository: docker.io/flikweertvision/fv-api
    tag: latest
    pullPolicy: IfNotPresent
  
  environment:
    machine_password: ""
    mssql_db_host: ""
    mssql_db_port: ""
    mssql_db_user: ""
    mssql_db_password: ""
    mssql_db_database: ""
    rmq_username: "fv_api"
    rmq_password: "fv_api"
    rmq_host: ""
    rmq_port: ""
    SECRET_KEY: ""

  volumes:
    - "./management_data:/python-docker/data"
    - "plc-backup:/plc_backups"
    - "plc-update:/plc_updates"
    - "nas-backup:/backups"

prometheus:
  replicaCount: 1

  image:
    repository: prom/prometheus
    tag: latest
    pullPolicy: IfNotPresent
  
alertmanager:
  replicaCount: 1
  
  image:
    repository: prom/alertmanager
    tag: v0.23.0
    pullPolicy: IfNotPresent

grafana:
  replicaCount: 1

  image:
    repository: grafana/grafana-enterprise
    tag: latest
    pullPolicy: IfNotPresent

rabbitmq:
  replicaCount: 1

  image:
    repository: rabbitmq
    tag: 4.0.2-management
    pullPolicy: IfNotPresent