apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-fwvconsumer
  labels:
    app: fwvconsumer
spec:
  replicas: {{ .Values.fwvconsumer.replicaCount }}
  selector:
    matchLabels:
      app: fwvconsumer
  template:
    metadata:
      labels:
        app: fwvconsumer
    spec:
      containers:
        - name: fwvconsumer
          image: "{{ .Values.fwvconsumer.image.repository }}:{{ .Values.fwvconsumer.image.tag }}"
        
          imagePullPolicy: "{{ .Values.fwvconsumer.image.pullPolicy }}"
          env:
            - name: POSTGRES_DB_HOST
              value: {{ include "fwv-central-api-chart.fullname" . }}-postgresdb
            - name: POSTGRES_DB_USER
              value: "{{ .Values.postgresdb.credentials.username }}"
            - name: POSTGRES_DB_PASSWORD
              value: "{{ .Values.postgresdb.credentials.password }}"
            - name: POSTGRES_DB_PORT
              value: "{{ .Values.postgresdb.service.port }}"
            - name: POSTGRES_DB_NAME
              value: postgres
            - name: MSSQL_DB_HOST
              value: "{{ .Values.mssql.host }}"
            - name: MSSQL_DB_USER
              value: "{{ .Values.mssql.credentials.user }}"
            - name: MSSQL_DB_PASSWORD
              value: "{{ .Values.mssql.credentials.pass }}"
            - name: MSSQL_DB_DATABASE
              value: "{{ .Values.mssql.database }}"
            - name: MSSQL_DB_PORT
              value: "{{ .Values.mssql.port }}"
            - name: RMQ_USERNAME
              value: "{{ .Values.fwvconsumer.environment.rmq_username }}"
            - name: RMQ_PASSWORD
              value: "{{ .Values.fwvconsumer.environment.rmq_password }}"
            - name: RMQ_HOST
              value: "{{ .Values.fwvconsumer.environment.rmq_host }}"
            - name: RMQ_PORT
              value: "{{ .Values.fwvconsumer.environment.rmq_port }}"
      imagePullSecrets:
        - name: flikweert-vision
