apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-fwvconsumer
  labels:
    app: fwvconsumer
spec:
  replicas: {{ .Values.fwvconsumer.replicaCount }}
  selector:
    matchLabels:
      app: fwvconsumer
  template:
    metadata:
      labels:
        app: fwvconsumer
    spec:
      containers:
        - name: fwvconsumer
          image: "{{ .Values.fwvconsumer.image.repository }}:{{ .Values.fwvconsumer.image.tag }}"
          imagePullPolicy: "{{ .Values.fwvconsumer.image.pullPolicy }}"
          env:
            - name: POSTGRES_DB_HOST
              value: "{{ .Values.fwvconsumer.environment.pg_db_host }}"
            - name: POSTGRES_DB_USER
              value: "{{ .Values.fwvconsumer.environment.pg_db_user }}"
            - name: POSTGRES_DB_PASSWORD
              value: "{{ .Values.fwvconsumer.environment.pg_db_password }}"
            - name: POSTGRES_DB_PORT
              value: "{{ .Values.fwvconsumer.environment.pg_db_port }}"
            - name: POSTGRES_DB_NAME
              value: "{{ .Values.fwvconsumer.environment.pg_db_name }}"
            - name: MSSQL_DB_HOST
              value: "{{ .Values.fwvconsumer.environment.mssql_db_host }}"
            - name: MSSQL_DB_USER
              value: "{{ .Values.fwvconsumer.environment.mssql_db_user }}"
            - name: MSSQL_DB_PASSWORD
              value: "{{ .Values.fwvconsumer.environment.mssql_db_password }}"
            - name: MSSQL_DB_DATABASE
              value: "{{ .Values.fwvconsumer.environment.mssql_db_database }}"
            - name: MSSQL_DB_PORT
              value: "{{ .Values.fwvconsumer.environment.mssql_db_port }}"
            - name: RMQ_USERNAME
              value: "{{ .Values.fwvconsumer.environment.rmq_username }}"
            - name: RMQ_PASSWORD
              value: "{{ .Values.fwvconsumer.environment.rmq_password }}"
            - name: RMQ_HOST
              value: "{{ .Values.fwvconsumer.environment.rmq_host }}"
            - name: RMQ_PORT
              value: "{{ .Values.fwvconsumer.environment.rmq_port }}"
        imagePullSecrets:
        - name: regcred