apiVersion: v1
kind: Service
metadata:
  name: {{ include "fwv-central-api-chart.fullname" . }}-pgadmin-service
spec:
  type: NodePort
  ports:
    - port: 5050
      targetPort: 80
      protocol: TCP
      nodePort: {{.Values.pgadmin.hostPort}}
  selector:
    app: {{ include "fwv-central-api-chart.name" . }}-pgadmin
