apiVersion: v1
kind: Service
metadata:
  name: {{ include "fwv-central-api-chart.fullname" . }}-rabbitmq
spec:
  type: NodePort
  ports:
    - name: http-api
      port: 15672
      targetPort: 15672
      protocol: TCP
      nodePort: {{.Values.rabbitmq.hostPort}}
    - name: amqp-client
      port: 5672
      targetPort: 15672
      protocol: TCP
      nodePort: {{.Values.rabbitmq.hostPort}}
    
  selector:
    app: {{ include "fwv-central-api-chart.name" . }}-rabbitmq
